### ISSUE TITLE
UriをinputStreamへ変換する際にエラーとなる

### ISSUE THREAD

**Issue by yagichan160** [yagichan160/recyclerview_prc#15]
DBに保存した、UriをinputStream変換しようとすると、以下のエラーが発生します。
Uriのスキームが影響しているのでしょうか？

こちらのサイトを見ると、スキーマによっては、ファイルパスの取得に一工夫する必要があるみたいな記載がありますが、、英語の解読で断念してしまいました。。

参考サイト
https://qiita.com/wakamesoba98/items/98b79bdfde19612d12b0#uri--file

Uri
”content://com.android.providers.media.documents/document/image%3A104”

エラーコード全文
```
 Process: com.example.myapplication, PID: 5660
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.activity.CreateMemo}: java.io.FileNotFoundException: No content provider: androidx.appcompat.widget.AppCompatImageView{9fa9e66 V.ED..... ........ 0,900-720,1232 #7f080080 app:id/picture_view}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2944)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6703)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.io.FileNotFoundException: No content provider: androidx.appcompat.widget.AppCompatImageView{9fa9e66 V.ED..... ........ 0,900-720,1232 #7f080080 app:id/picture_view}
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1444)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1295)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:1015)
        at com.example.myapplication.activity.CreateMemo.onCreate(CreateMemo.kt:49)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3079) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1836) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6703) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
```

**Comment by friegen** [comment]
簡単にデバッグしてみて確認してみました。  
ちゃんとUriが保存できているかを確認してみてください。

**Comment by yagichan160** [comment]
有難うございます。
PRでも同じ質問をしてしまいました。。すみません。

id?.pictureに正しくUriが保存されているか確認してみます。

ちなみに、、inputStreamへ変換する際に、、Uriを加工する必要はあるのでしょうか？
override fun onActivityResult 内では特に何もしていないと思うので不要だとは思っているのですが。
※以下を気にしてます。

> こちらのサイトを見ると、スキーマによっては、ファイルパスの取得に一工夫する必要があるみたいな記載がありますが、、英語の解読で断念してしまいました。。
> 
> 参考サイト
> https://qiita.com/wakamesoba98/items/98b79bdfde19612d12b0#uri--file
>

**Comment by friegen** [comment]
この辺、ちょっと疎いのですが、画像をIntentで選択したあとにImageViewには反映されているのでUriは多分加工しなくて良いんじゃないかなぁと思います。
ただ、DBに入れるときはStringにすると思うんで、DBから取得してきたときはString→Uriにする必要はあると思います（現状、Uri.parseしているので問題ないと思っています。）

**Comment by friegen** [comment]
ちなみに、原因はこれです。
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.activity.CreateMemo}: java.io.FileNotFoundException: No content provider: androidx.appcompat.widget.AppCompatImageView{9fa9e66 V.ED..... ........ 0,900-720,1232 #7f080080 app:id/picture_view}
```

`androidx.appcompat.widget.AppCompatImageView{9fa9e66 V.ED..... ........ 0,900-720,1232 #7f080080 app:id/picture_view}` なんてファイル無ぇよ！って言われてます。

**Comment by yagichan160** [comment]
ここの記載がおかしい気がします。。
picture_viewからuriを抜き出すにはどうすれば良いのか・・・

‘‘‘
save.setOnClickListener {

            val text = write_area.text.toString()
            val title = title_area.text.toString()
            val pic = picture_view.toString()　←これだと、、imageviewそのものを文字列で抽出しちゃう・・・。
‘‘‘

**Comment by yagichan160** [comment]
あ、、、picture_viewからbitmapを取得し、
それをUriに変換してやれば良さそうですね。試してみます。

**Comment by tsutomu-dobashi** [comment]
Intentから渡されてきたUriを直接保持しちゃだめですか？
アプリ内に画像データを置きたい？

**Comment by friegen** [comment]
Intentから渡されてきたUriを直接保持しちゃだめですか？
アプリ内に画像データを置きたいです？

**Comment by yagichan160** [comment]
該当のメモデータを開くたびにimageviewへ画面が表示されるようにしたいです。
なので、こちらに該当するかなと思います。
>>アプリ内に画像データを置きたいです？

とはいいつつも、Intentから渡されたUriを保持する方法もわかっていません。。
ovveride fun onActivityResult内のpicture.data=Uriだと思うのですが、
これを使ってどうやってDBへアクセスすれば良いのかがわかっていません、、、。

**Comment by friegen** [comment]
> 該当のメモデータを開くたびにimageviewへ画面が表示されるようにしたいです。

普通にメンバ変数で

private var uri:Uri? = null

で用意しておいて、Intentから渡されてきたタイミングで保持してはだめですか？

アプリ内で画像データを保存しておきたいのであれば

```
                    picturedata?.data?.also { uri ->

                        val inputStream = contentResolver?.openInputStream(uri)
                        val image = BitmapFactory.decodeStream(inputStream)
                        val imageView = findViewById<ImageView>(R.id.picture_view)
                        imageView.setImageBitmap(image)
                    }
```

val imageがBitmapになっているので、このタイミングでローカルストレージに保存するのが良いかなぁって思います。
（ここでやるのが一番楽かなって・・・）

**Comment by yagichan160** [comment]
↓の｛｝内で、val imageをstringへ変換し、DBへ保存する。
ということでしょうか？
（確かにここが一番楽そうですが、DBへのアクセス方法が想像ついてないです、、、）

```
picturedata?.data?.also { uri ->

                        val inputStream = contentResolver?.openInputStream(uri)
                        val image = BitmapFactory.decodeStream(inputStream)
                        val imageView = findViewById<ImageView>(R.id.picture_view)
                        imageView.setImageBitmap(image)
                    }
````

**Comment by friegen** [comment]
違います。

## Intentから渡されてきたUriの保持するパターン

`picturedata?.data?.also { uri ->`
画像のUriがIntentから渡されてくるのでメンバ変数を用意しておき保持。

`private var imageUri:Uri? = null`

```
picturedata?.data?.also { uri ->
                          imageUri = uri  // ここで保持したimageUriをDB保存時に使用する
                    }
```

## 画像データをアプリ内に保持するパターン
```
picturedata?.data?.also { uri ->

                        val inputStream = contentResolver?.openInputStream(uri)
                        val image = BitmapFactory.decodeStream(inputStream)   // ←この時点でBitmapになっている
                        val imageView = findViewById<ImageView>(R.id.picture_view)
                        imageView.setImageBitmap(image)
                    }
```

UriをBitmap変換したあとにBitmapを保存する処理を書く
```
private fun saveBitmap(bitmap:Bitmap):Uri(Stringとか){
    // 保存処理
}
```

保存処理を作成する際にUri（FilePath）を作成するはずなので、その作成したUriを保持する。

ファイル保存の仕方は調べてみてください。

**Comment by yagichan160** [comment]
有難うございます。
どちらも試してみようと思います。。

ちなみに、、初歩的な質問で申し訳ないのですが、、
以下の「Intentから渡されてきたUriの保持するパターン」の場合、
｛｝の外でimageUriを使用することはできるのでしょうか？
スレッド?が別だから無理でしょうか？

```
picturedata?.data?.also { uri ->
                          imageUri = uri  // ここで保持したimageUriをDB保存時に使用する
                    }
```

**Comment by friegen** [comment]
`private lateinit var viewmodel: CreateViewModel`
の下にでも
`private var imageUri:Uri? = null`
を書けばよいです。

C# でいうフィールド変数です。
フィールド変数っていうのかメンバ変数っていうのかは現場によって違う気がしますけど。。。
自分はメンバ変数っていう派ですｗ
https://qiita.com/toshi0607/items/801a0d37fb48313cbdbd


> どちらも試してみようと思います。。

アプリの仕様となるので、このアプリにとってどちらがベストかを考えてみてください。

**Comment by yagichan160** [comment]
なるほど。理解できました！
どちらも試しつつ、自分の構想に近い方を採用したいと思います！
（順序が逆ですが、個人アプリということで・・・）
さっそくこれからやってみます。

**Comment by friegen** [comment]
大丈夫そうならCloseしてもらえますか？
